# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: test-secret-key
      ENCRYPTION_KEY: b'1wIZtgNb5qhYAZHy6HWkJ-TTeMq39mOq0P4gIFJUUg8='

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13.9"]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tesseract-ocr tesseract-ocr-eng
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify imports
      run: |
        python -c "import app"

    - name: Start Flask Server
      run: |
        python app.py &
        sleep 15

    - name: Health check
      run: |
        curl http://localhost:8080/login
